services:
  sookshma:
    environment:
      - CYCLONEDDS_URI=file:///workspaces/mavlab/.devcontainer/cyclonedds_lan.xml

  rosbridge:
    environment:
      - CYCLONEDDS_URI=file:///workspaces/mavlab/.devcontainer/cyclonedds_lan.xml

