# Base: ZED SDK 5.0 for JetPack 6.2.1 (L4T r36.4)
FROM stereolabs/zed:5.0-tools-devel-l4t-r36.4

# -------------------- ROS 2 Humble + Base Deps --------------------
RUN apt-get update && apt-get install -y curl gnupg2 lsb-release \
 && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg \
 && echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
    http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
    > /etc/apt/sources.list.d/ros2.list \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      ros-humble-ros-base \
      python3-rosdep \
      python3-vcstool \
      python3-colcon-common-extensions \
      build-essential \
 && rosdep init || true \
 && rosdep update \
 && rm -rf /var/lib/apt/lists/*

# -------------------- Additional Apt Packages --------------------
RUN apt-get update && apt-get install -y software-properties-common \
 && apt-add-repository -y universe && apt-get update \
 && apt-get install -y --no-install-recommends \
      python3-pip python3-serial python3-venv python3-opencv \
      sudo xauth htop udev zip unzip curl \
      libboost-all-dev libasio-dev \
      build-essential gcc gfortran git \
      libsm6 libxext6 libxrender1 libfontconfig1 libgl1 libpcl-dev libpcap-dev libopencv-dev libyaml-cpp-dev libeigen3-dev gdebi-core \
      ros-humble-diagnostic-updater \
      ros-humble-nmea-msgs \
      ros-humble-rtcm-msgs \
      ros-humble-rviz2 \
      ros-humble-rosbridge-server \
      ros-humble-rosx-introspection \
      ros-humble-foxglove-bridge \
      ros-humble-image-transport \
      ros-humble-image-transport-plugins \
      ros-humble-compressed-image-transport \
      ros-humble-compressed-depth-image-transport \
      ros-humble-theora-image-transport \
      ros-humble-point-cloud-transport-plugins \
      ros-humble-draco-point-cloud-transport \
      ros-humble-zlib-point-cloud-transport \
      ros-humble-zstd-point-cloud-transport \
      ros-humble-xacro \
      ros-humble-vision-opencv \
      ros-humble-ffmpeg-image-transport \
      ros-humble-ffmpeg-encoder-decoder \
      ros-humble-zed-msgs \
      ros-humble-geographic-msgs \
      ros-humble-point-cloud-transport \
      ros-humble-pcl-conversions \
      ros-humble-robot-localization \
      ros-humble-backward-ros \
      ros-humble-tf2-ros \
      ros-humble-tf2-geometry-msgs \
      ros-humble-message-filters \
      ros-humble-camera-info-manager \
      ros-humble-pointcloud-to-laserscan \
      ros-humble-laser-filters \
      gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi bossa-cli \
 && ln -sf /usr/bin/python3 /usr/bin/python \
 && chmod -R a+rX /usr/local/lib/python3.10/dist-packages /usr/lib/python3/dist-packages \
 && rm -rf /var/lib/apt/lists/*

# -------------------- Create non-root user --------------------
ARG USERNAME=mavlab
ENV USERNAME=${USERNAME}
RUN useradd -m "${USERNAME}" \
 && echo "${USERNAME}:${USERNAME}" | chpasswd \
 && usermod --shell /bin/bash "${USERNAME}" \
 && usermod -aG sudo,dialout,video,plugdev,zed "${USERNAME}" \
 && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
 && chmod 0440 /etc/sudoers.d/${USERNAME}

# -------------------- Python venv + pip packages --------------------
USER ${USERNAME}
WORKDIR /home/${USERNAME}
RUN python3 -m venv --system-site-packages /home/${USERNAME}/.venv
ENV VIRTUAL_ENV=/home/${USERNAME}/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
COPY --chown=${USERNAME}:${USERNAME} requirements.txt /home/${USERNAME}/requirements.txt
RUN python3 -m pip install --upgrade pip setuptools wheel \
 && python3 -m pip install --no-cache-dir -r /home/${USERNAME}/requirements.txt
RUN echo 'source $VIRTUAL_ENV/bin/activate' >> ~/.bashrc

# -------------------- Sensor ROS Packages to home/mavlab/ros2_ws --------------------

COPY --chown=${USERNAME}:${USERNAME} packages /home/${USERNAME}/ros2_ws/src
WORKDIR /home/${USERNAME}/ros2_ws

USER root
WORKDIR /home/mavlab/ros2_ws
RUN apt-get update && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y
USER ${USERNAME}

# -------------------- Install ping-python/brping --------------------
USER root
WORKDIR /home/${USERNAME}/ros2_ws/src/ping_sonar_ros/ping_sonar_ros/ping-python
RUN /usr/bin/python3 setup.py install
USER ${USERNAME}

# -------------------- Build the sensor ROS Packages once and available directly inside container --------------------
USER root
WORKDIR /home/${USERNAME}/ros2_ws
RUN bash -c "source /opt/ros/humble/setup.bash && \
             colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release --parallel-workers $(nproc)"

# -------------------- ROS 2 bashrc + aliases --------------------
RUN echo 'source /opt/ros/humble/setup.bash' >> /home/${USERNAME}/.bashrc \
 && echo 'if [ -f /home/mavlab/ros2_ws/install/setup.bash ]; then source /home/mavlab/ros2_ws/install/setup.bash; fi' >> /home/${USERNAME}/.bashrc \
 && echo 'if [ -f /workspaces/mavlab/code_ws/install/setup.bash ]; then source /workspaces/mavlab/code_ws/install/setup.bash; fi' >> /home/${USERNAME}/.bashrc \
 && echo "alias sros2='source /opt/ros/humble/setup.bash && source /home/mavlab/ros2_ws/install/setup.bash'" >> /home/${USERNAME}/.bashrc \
 && echo "alias scode='source /opt/ros/humble/setup.bash && source /workspaces/mavlab/code_ws/install/setup.bash'" >> /home/${USERNAME}/.bashrc \
 && echo "alias colb='pushd /workspaces/mavlab/code_ws >/dev/null && sudo rm -rf build log install && colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release --parallel-workers \$(nproc) && sros2 && popd >/dev/null'" >> /home/${USERNAME}/.bashrc \
 && echo "alias topics='ros2 topic list'" >> /home/${USERNAME}/.bashrc \
 && echo "alias nodes='ros2 node list'" >> /home/${USERNAME}/.bashrc

RUN echo "alias sbg='ros2 launch sbg_driver sbg_device_launch.py'" >> /home/${USERNAME}/.bashrc \
 && echo "alias gnc='ros2 run gnc gnc'" >> /home/${USERNAME}/.bashrc \
 && echo "alias mavsim='ros2 run mav_simulator simulate'" >> /home/${USERNAME}/.bashrc \
 && echo "alias zed='ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zed2i '" >> /home/${USERNAME}/.bashrc \
 && echo "alias dvl='ros2 launch dvl_a50 dvl_a50.launch.py ip_address:='192.168.194.95''" >> /home/${USERNAME}/.bashrc \
 && echo "alias ping360='ros2 run ping360_sonar ping360.py --ros-args -p device:=/dev/ping360'" >> /home/${USERNAME}/.bashrc \
 && echo "alias ping2='ros2 run ping_sonar_ros ping1d_node --ros-args -p port:=/dev/ping2'" >> /home/${USERNAME}/.bashrc

# -------------------- Expose Ports --------------------
EXPOSE 9000 9001 9002 9003
